export const skills = [
  { label: 'Python', value: 95 },
  { label: 'SQL / NoSQL', value: 92 },
  { label: 'TypeScript / JavaScript', value: 90 },
  { label: 'APIs', value: 88 },
  { label: 'System Design', value: 90 },
  { label: 'ETL Pipelines', value: 90 },
  { label: 'Version Control (Git)', value: 92 },
  { label: 'Google Cloud Platform', value: 87 },
  { label: 'AI Agents', value: 85 },
  { label: 'Docker', value: 80 },
  { label: 'AWS', value: 75 },
  { label: 'Data Warehousing', value: 82 },
  { label: 'CI/CD', value: 85 },
  { label: 'Terraform', value: 70 },
  { label: 'Deep Learning', value: 70 },
];